version: "3.3"

services:
  postgres_db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "myPrueba"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    networks:
      postgres_network:
        aliases:
          - postgres_host
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=imendoza@unab.edu.co
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      postgres_network:
        aliases:
          - postgres_host
  mysql_db:
    image: mysql:5
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=myPrueba
      - MYSQL_PORT=3306
    ports:
      - "3306:3306"

networks:
  postgres_network:
    driver: bridge

