version: "3.3"

services:
  postgres_db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "myPrueba"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    networks:
      postgres_network:
        aliases:
          - postgres_host
networks:
  postgres_network:
    driver: bridge

